# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  working_directory: /tmp/salad-rabbit
  docker:
    - image: circleci/node:8

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Deps
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: /tmp
          paths:
            - salad-rabbit
workflows:
  version: 2
  test-build:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only:
                - /renovate.*/
      - build:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - /renovate.*/