# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  working_directory: /tmp/salad-rabbit
  docker:
    - image: circleci/node:8@sha256:23f55ec43b896824088c2dcd6b0f88b7c34c6f7e5fa761d98244a5ef434f93e1

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
      - run:
          name: Install Deps
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: /tmp
          paths:
            - salad-rabbit
  get_dev_env_config:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Pull config file and write to disk
          command: CONFIG_CONTEXT='dev' yarn run get-config
      - persist_to_workspace:
          root: /tmp
          paths:
            - salad-rabbit
  dev_build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Build Project
          command: yarn run build
      - persist_to_workspace:
          root: /tmp
          paths:
            - salad-rabbit
  deploy_to_dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: DEV deploy
          command: scp -oStrictHostKeyChecking=no -r dist/* sweet@sr.shaunsweet.com:/var/www/sr.shaunsweet.com/
workflows:
  version: 2
  build-n-deploy-dev:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only:
                - master
      - get_dev_env_config:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - master
      - dev_build:
          requires:
            - install_dependencies
            - get_dev_env_config
          filters:
            branches:
              only:
                - master
      - deploy_to_dev:
          requires:
            - dev_build
          filters:
            branches:
              only:
                - master
  test-build:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only:
                - /renovate.*/
      - get_dev_env_config:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - /renovate.*/
      - dev_build:
          requires:
            - install_dependencies
            - get_dev_env_config
          filters:
            branches:
              only:
                - /renovate.*/